### PR TITLE
Fix CI test failures in remoteHeads.test.ts

### LINKED ISSUE #275: Intermittent CI test failures
The test action failed twice on #274, and passed the third time I ran it: 

❌ [Attempt #1](https://github.com/automerge/automerge-repo/actions/runs/7603968031/job/20706319740)
❌ [Attempt #2](https://github.com/automerge/automerge-repo/actions/runs/7603968031/job/20719542932)
✅ [Attempt #3](https://github.com/automerge/automerge-repo/actions/runs/7603968031/job/20719597238)

In all cases the tests are all passing, but Vitest fails the test run if any errors are thrown after the test environment is torn down. 

```
⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯
Unknown Error: bad theirHave: error loading have at index 0: bad bloom: the value was not a Uint8Array
This error originated in "packages/automerge-repo/test/remoteHeads.test.ts" test file. It doesn't mean the error was thrown inside the file itself, but while it was running.
This error was caught after test environment was torn down. Make sure to cancel any running tasks before test finishes:
- cancel timeouts using clearTimeout and clearInterval
- wait for promises to resolve using the await keyword
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 Test Files  15 passed (15)
      Tests  164 passed (164)
     Errors  1 error
```

I haven't been able to reproduce the failure locally, so it may have something to do with the CI runner being a bit slower than my laptop. This bit in the setup function looks suspicious to me: 

https://github.com/automerge/automerge-repo/blob/b87785a01e0b2944feea49b2342c960e09cf1c32/packages/automerge-repo/test/remoteHeads.test.ts#L89-L96

There are similarly arbitrary pauses in the tests themselves:

https://github.com/automerge/automerge-repo/blob/b87785a01e0b2944feea49b2342c960e09cf1c32/packages/automerge-repo/test/remoteHeads.test.ts#L112-L116

### PR DESCRIPTION
**Pull request by HerbCaudill**
fixes #275 

I was never able to reproduce the error locally, but I've removed all arbitrary timeouts (100ms, 200ms, etc) from the test suite. I've [run the test action 10 times](https://github.com/automerge/automerge-repo/actions/runs/7610581777?pr=277) and it's passed each time, so I'm going to assume that did the trick.

### CODE REVIEW

File: packages/automerge-repo/test/helpers/collectMessages.ts [hunk 1]
```diff
@@ -0,0 +1,19 @@
+import { EventEmitter } from "eventemitter3"
+import { pause } from "../../src/helpers/pause.js"
+
+export async function collectMessages({
+  emitter,
+  event,
+  until = pause(100),
```
Comment (HerbCaudill) [inline packages/automerge-repo/test/helpers/collectMessages.ts:7]: Rather than passing a timeout in ms, this gives the option of collecting messages until some other event occurs, e.g. 

```ts
await collectMessages({
  emitter: aliceTab2.networkSubsystem,
  event: "message",
  until: aliceTab2DocA.whenReady(),
})
```

Comment (pvh) [reply packages/automerge-repo/test/helpers/collectMessages.ts:7]: Nice!

**Review by pvh — APPROVED** [review]
